# Generated by Django 4.2.18 on 2025-02-04 03:57

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='YtVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_name', models.CharField(max_length=400, null=True)),
                ('slug', models.SlugField(blank=True, max_length=450, null=True, unique=True)),
                ('video_type', models.CharField(blank=True, choices=[('YouTube', 'YouTube'), ('Hosted', 'Hosted')], default='YouTube', max_length=100, null=True)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='youtube/thumbnail/%Y/%m/%d/')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='youtube/photo/%Y/%m/%d/')),
                ('ytvideo_link', models.URLField(blank=True, max_length=600, null=True)),
                ('ytvideo_code', models.CharField(blank=True, max_length=300, null=True)),
                ('ytplay_code', models.CharField(blank=True, default='?autoplay=1', max_length=300, null=True)),
                ('embed_code', models.TextField(blank=True, null=True)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Publish')], default=0)),
                ('categories', mptt.fields.TreeManyToManyField(related_name='ytvideos', to='recipes.category')),
                ('recipe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='recipes.recipe')),
            ],
            options={
                'verbose_name': 'YouTube Video',
                'verbose_name_plural': ' YouTube Videos',
            },
        ),
    ]
